### PR TITLE
replace humbug with infection

### PR DESCRIPTION
**Pull request by JanPietrzyk**
If infection wins the mutation testing war, we can now easily switch

### CODE REVIEW

**Comment by theofidry** [comment]
Regardless of your choice, don't put PHARs in a git repository. They have a monstrous footprint. Either use https://github.com/tommy-muehle/tooly-composer-script or https://github.com/bamarni/composer-bin-plugin.

Also keep in mind that the code bundled in PHARs is not isolated, so you can run in unexpected conflicts. While this problem can be fixed in the future, in the meantime it may be wiser to require it as a dev dependency

**Comment by JanPietrzyk** [comment]
>  don't put PHARs in a git repository

Nice opinion you have there. Here is another one: Currently there is no clear winner in the bin plugin space either so adding phar archives to the environment looks like a pragmatic decision to me. (And by the way, my hopes go to https://github.com/phar-io)

> may be wiser to require it as a dev dependency

been there done that :) I remember quite vividly the dependency hell we got from the 2.x to 3.x Symfony release switch. Although the code is not properly isolated my - pragmatic - observation was that this rarely mattered. 

The most important problem arises here from incompatibilities between different dev concerns. In another project we use a whole suite off different and independent php binaries for quality assurance. `php-cs-fixer`, `deptrac` and the like may use different symfony requirements but are run independently and so have no problems.

Last but not least: If a problem you describe arises it is local to a specific binary, can easily be tracked and resolved. CI to the rescue :)

**Comment by theofidry** [comment]
>Currently there is no clear winner in the bin plugin space either so adding phar archives to the environment looks like a pragmatic decision to me

There is not need for a winner there: both works just pick one :)

There is two issues with PHARs commited:

- inherent to the PHARs: the bundled code is not isolated unless you distribute a PHAR with isolated code thanks to a custom builder or a more generic one like [PHP-Scoper](https://github.com/humbug/php-scoper). The former is a PITA and the later is quite new so not widely used. As a result it's pretty much as if you were copy/pasting code and hope it's compatible: not always. The PHPUnit 5.x to 6.x is one case, another is PHP-Parser also quite common.
- it is _huge_ and is a major slowdown perf wise whenever you clone/commit

I mentioned two solutions but I could rather come up with 4:

- [bamarni/composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin): a very elegant way to manage multiple `composer.json` files which allows you to leverage composer and requires no extra tooling
- [tommy-muehle/tooly-composer-script](https://github.com/tommy-muehle/tooly-composer-script): good enough if you just want to download a PHAR, but no way to version it or anything
- [phar.io](https://github.com/phar-io): I honestly didn't have the time to play with it yet and as I'm still mostly using bamarni/composer-bin-plugin for various reasons, it is not urgent either
- scripts: a Makefile or something that downloads the PHARs as you need. A comparable example is [here](https://github.com/nelmio/alice/blob/master/Makefile#L65) where I install PHP-CS-Fixer in a different `composer.json` thanks to bamarni/composer-bin-plugin automatically when runnnig the `make cs` command

So there is actually plenty of good solutions. None are perfect, but IMO they are all way better than committing a PHAR directly in the Git repository.

>php-cs-fixer, deptrac and the like may use different symfony requirements but are run independently and so have no problems.

That's not the main issue here but for the record I prefer to keep those kind of tools in a different `composer.json` or as PHARs for two reasons:

- it's silly to get dependency conflicts when they are actually not dependent, neither between themselves or with your application/library
- in a library, the more dev constraints you add the greater the difference will be between what you test as a maintainer or your CI and what the consumer get. For example if you have a required dep which is `symfony/yaml: ^2.8||^3.0` and a dev deps has `symfony/yaml: ^3.0`, you will actually never test your library under `symfony/yaml [2.8.0, 3.0.0[` which _may_ be an issue

>If a problem you describe arises it is local to a specific binary, can easily be tracked and resolved

I had two issues with it, was really hard to debug and fix, never again :P But then yes it's also not very common, so it's completely up to you. It's not a problem always worth to fight against

**Comment by teiling88** [comment]
I think we can merge it :-) https://github.com/humbug/humbug/commit/53730b3306efebf85bd66b6f7ec870d500f5ccbd

**Comment by JanPietrzyk** [comment]
no longer active

**Pull request closed without merging**
