### PR TITLE
Add action token

### PR DESCRIPTION
**Pull request by nlubisch**
This adds a new token called "ACTION" as pointed out in my issue #83.

```bash
#!/usr/bin/env bash

ACTION: shopware:update # Reference to dev-ops/shopware/actions/update.sh
ACTION: unit # Reference to dev-ops/common/actions/unit.sh
```

### CODE REVIEW

**Comment by nlubisch** [comment]
@teiling88 @JanPietrzyk also here, if this looks good to you i fix the tests :)

**Comment by JanPietrzyk** [comment]
@nlubisch looks good. Please remember to check scrutinizer too

**Comment by teiling88** [comment]
@nlubisch and add some lines in the README.md please :-)

**Comment by nlubisch** [comment]
* Fixed existing tests
* Added new tests for the action token
* Fixed error output for ScriptNotFoundException
* Added instructions to README.md

This should now be good to go, @JanPietrzyk  :)

**Review by JanPietrzyk — CHANGES_REQUESTED** [review]
Hey, sorry for the delay. Looked for the first time through your tests. Wouldn't it be possible to test this more in the style of the `INCLUDE` token? IMHO this would also be sufficient and grant us more flexibility when refactoring the application.

**Review by JanPietrzyk — APPROVED** [review]

**Pull request merged**
